[build]
  command = "CI= npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run start"
  targetPort = 3000
  port = 8888
  publish = "build" 